before_install:
- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
- unzip awscliv2.zip
- sudo ./aws/install
# Setup for deployment

script: 
  #Begins configuration for shared files
  - VERSION=main
  - echo "$SHARED_CICD_DEPLOY_KEY" > ~/.ssh/cicd_pipelines_deploy_key
  - chmod 400 ~/.ssh/cicd_pipelines_deploy_key
  - GIT_SSH_COMMAND='ssh -i ~/.ssh/cicd_pipelines_deploy_key -o IdentitiesOnly=yes' git clone git@github.com:perzam/demo-travis.git --depth 1  --branch $VERSION
  - cp -r cicd_pipelines/kubernetes/travis_scripts .
  - cp -r cicd_pipelines/travis_common_scripts .
  #Ends configuration for shared files

deploy:
# DEV deploy
  - provider: script
    script: bash travis_scripts/build.sh
    on:
      branch: main
    skip_cleanup: true
